version: '3'
services:
  email-sender:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "EMAIL_HOST=smtp.gmail.com"
      - "EMAIL_PORT=587"
      - "EMAIL_USERNAME=lakshyabhardwaj200315@gmail.com"
      - "EMAIL_PASSWORD=xvfhpwyjodvcucbe"
      - "EMAIL_SMTP_AUTH=true"
      - "EMAIL_SMTP_STARTTLS_ENABLE=true"
    volumes:
      - "./src/main/resources/static:/usr/local/tomcat/webapps/ROOT"
    restart: always